#ifndef DSPDMA_H
#define DSPDMA_H

#define DSPDMA_TYPE *((volatile uint32_t *) 0xF0020000)
#define DSPDMA_INDEX *((volatile uint32_t *) 0xF0020004)
#define DSPDMA_PARAM0 *((volatile uint32_t *) 0xF0020008)
#define DSPDMA_PARAM1 *((volatile uint32_t *) 0xF002000C)
#define DSPDMA_PARAM2 *((volatile uint32_t *) 0xF0020010)
#define DSPDMA_PARAM3 *((volatile uint32_t *) 0xF0020014)
#define DSPDMA_COMMAND *((volatile uint32_t *) 0xF0020020)
#define DSPDMA_TRANSFER_SIZE *((volatile uint32_t *) 0xF0020024)

#define DSPDMA_SOURCE_TYPE_NONE 0
#define DSPDMA_SOURCE_TYPE_MEM8 1
#define DSPDMA_SOURCE_TYPE_MEM16 2
#define DSPDMA_SOURCE_TYPE_MEM32 3

#define DSPDMA_DEST_TYPE_NONE 0
#define DSPDMA_DEST_TYPE_MEM8 1
#define DSPDMA_DEST_TYPE_MEM16 2
#define DSPDMA_DEST_TYPE_MEM32 3

#define DSPDMA_OP_TYPE_END 0
#define DSPDMA_OP_TYPE_COPY 1

#define DSPDMA_COMMAND_TRIGGER 0
#define DSPDMA_COMMAND_WRITE_SOURCE 1
#define DSPDMA_COMMAND_WRITE_DEST 2
#define DSPDMA_COMMAND_WRITE_PROGRAM_OP 3

#define DSPDMA_IOP_SOURCE_TYPE_SOURCE 0
#define DSPDMA_IOP_SOURCE_TYPE_IBUFFER 1
#define DSPDMA_IOP_SOURCE_TYPE_CONST 2

#define DSPDMA_IOP_DEST_TYPE_DEST 0
#define DSPDMA_IOP_DEST_TYPE_IBUFFER 1

#define DSPDMA_ERROR_NONE 0
#define DSPDMA_ERROR_INDEX_OUT_OF_RANGE 1
#define DSPDMA_ERROR_TYPE_OUT_OF_RANGE 2
#define DSPDMA_ERROR_PARAM0_OUT_OF_RANGE 3
#define DSPDMA_ERROR_PARAM1_OUT_OF_RANGE 4
#define DSPDMA_ERROR_PARAM2_OUT_OF_RANGE 5
#define DSPDMA_ERROR_SOURCE_OVERLAPS_PERIPHERAL 6
#define DSPDMA_ERROR_DEST_OVERLAPS_PERIPHERAL 7
#define DSPDMA_ERROR_TRANSFER_SIZE_TOO_LARGE 8
#define DSPDMA_ERROR_BAD_COMMAND 9
#define DSPDMA_ERROR_SOURCE_OUT_OF_RANGE 10
#define DSPDMA_ERROR_DEST_OUT_OF_RANGE 11
#define DSPDMA_ERROR_IOP_SOURCE_TYPE_OUT_OF_RANGE 12
#define DSPDMA_ERROR_IOP_DEST_TYPE_OUT_OF_RANGE 13
#define DSPDMA_ERROR_USAGE_OF_NULL_SOURCE 14
#define DSPDMA_ERROR_USAGE_OF_NULL_DEST 15
#define DSPDMA_ERROR_MEMORY_ACCESS 80

#define DSPDMA_MEM_ACCESS_ERROR_TYPE_READ 0
#define DSPDMA_MEM_ACCESS_ERROR_TYPE_WRITE 0

#endif
