[package]
name = "rv_vsys"
version = "0.1.0"
authors = ["Liam Taylor <witaylo@microsoft.com>"]
edition = "2018"

[features]
default = []
cpu_debug = []

[dependencies]
byteorder = "1"
num = "0.2"
num-derive = "0.3"
num-traits = "0.2"
parking_lot = "0.11"
